In [119]:
#installation of required libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re,json

In [120]:
#listing required links
url_list=['https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc']

for i in ('51','101','151','201'):
    url_list.append(f'https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc&start={i}&ref_=adv_nxt')

In [121]:
#function for pulling, categorizing and saving data
no=[]
name=[]
year=[]

def crawl(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html.parser')
    gelen_veri=soup.find_all("h3",{"class":"lister-item-header"})
    soup2=BeautifulSoup(str(gelen_veri),"html.parser")

    
    for i in soup2.find_all("span",{ "class" : "lister-item-index unbold text-primary"}):
        no.append(i.text.replace('.',''))
    
    
    for i in soup2.find_all("a"):
           name.append(i.text)

    
    for i in soup2.find_all("span",{ "class" : "lister-item-year text-muted unbold"}):
           year.append(i.text.replace('(','').replace(')',''))
    
    return(no,name,year)

In [122]:
#apply function for all url's
for url in url_list:
    crawl(url)

In [124]:
imdb=pd.DataFrame({'no':no,'name':name,'year':year})
imdb

      no                           name  year
0      1       The Shawshank Redemption  1994
1      2                  The Godfather  1972
2      3                The Dark Knight  2008
3      4         The Godfather: Part II  1974
4      5                   12 Angry Men  1957
..   ...                            ...   ...
245  246             Gone with the Wind  1939
246  247          It Happened One Night  1934
247  248     La passion de Jeanne d'Arc  1928
248  249  Sunrise: A Song of Two Humans  1927
249  250                    The General  1926

[250 rows x 3 columns]